name: Update Changelog

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install auto-changelog
        run: npm install -g auto-changelog

      - name: Generate Changelog
        run: auto-changelog --commit-limit false

      - name: Commit Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci]" || echo "No changes to commit"
          git push